---
if: drone
delimiters: ['[[', ']]']
---
---
kind: pipeline
name: default

steps:
- name: build
  image: golang:latest
  volumes:
  - name: deps
    path: /go
  commands:
  - make

- name: test
  image: golang:latest
  volumes:
  - name: deps
    path: /go
  commands:
  - make test

- name: linter
  image: golang:latest
  volumes:
  - name: deps
    path: /go
  commands:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.16.0
    - ./bin/golangci-lint run

[[ if .drone_telegram ]]
- name: telegram
  image: appleboy/drone-telegram
  settings:
    to: [[ .drone_telegram_chan ]]
    format: markdown
    token:
      from_secret: telegram_token
    message: >
      *{{repo.name}}*  

      [Build {{build.number}}]({{build.link}}) by {{commit.author}} {{#success build.status}}succeeded{{else}}failed{{/success}} in {{buildtime build.started}}  

      `{{truncate commit.sha 8}}`: "{{commit.message}}"
[[ end ]]
volumes:
- name: deps
  host:
    path: /var/lib/cache/godeps/