name: "Drone Template"
version: "0.1.0"
description: "Helps you generate a .drone.yml file that fits your project needs"
delimiters: ["[[", "]]"]
variables:
  name:
    prompt: "What's the name of your repo?"
    required: true
  organization:
    prompt: "What's your username or organization's name?"
    required: true
  gitserver:
    default: "github.com"
    help: "Git server"
  goversion:
    default: "latest"
    prompt: "Which go version should be used?"
  gomodules:
    confirm: false
    prompt: "Use gomodules instead of dep?"
  linter:
    confirm: true
    prompt: "Use golangci-lint as the main linter?"
  slack:
    confirm: true
    prompt: "Add Slack integration?"
    variables:
      channel:
        required: true
        help: "Channel in which the build result should be posted. Should start with a # to work properly"
        prompt: "Slack channel:"
      webhook:
        required: true
        help: "See https://api.slack.com/incoming-webhooks for more information"
        prompt: "Provide the Slack webhook URL:"
      username:
        prompt: "Username the integration will use to post in the channel:"
  tags:
    confirm: true 
    prompt: "Clone with tags?"
  
