{
 "title": "[[ .name ]]",
 "description": "[[ .name ]] Monitoring",
 "tags": [
  "application",
  "api",
  "gin"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "project", "label": "Project", "query": "[[ .name ]]" }
  ]
 },
 "panels": [
  { "title": "Request Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(${project}_requests_total{}[5m])) by (path,method)",
     "legendFormat": "{{ method }} {{ path }}"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "OK Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(${project}_requests_total{code=~\"^2..$\"}[5m])",
     "legendFormat": "{{ code }} {{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "4XX Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(${project}_requests_total{code=~\"^4..$\"}[5m])",
     "legendFormat": "{{ code }} {{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "5XX Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(${project}_requests_total{code=~\"^5..$\"}[5m])",
     "legendFormat": "{{code }} {{ method }} {{ path }}"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "${project}_request_duration_seconds{}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Health",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(${project}_requests_total{path=\"/health\", code=\"200\"}[5m]))",
     "legendFormat": "Health Check"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Go Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"${project}_.*\"}",
     "legendFormat": "Alloc Heap"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"${project}_.*\"}",
     "legendFormat": "In-Use Heap"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"${project}_.*\"}",
     "legendFormat": "In-Use Stack"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"${project}_.*\"}[30s])",
     "legendFormat": "Alloc Rate"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Reported memory usage by the OS",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=~\"${project}_.*\"}",
     "legendFormat": "Virtual"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"${project}_.*\"}",
     "legendFormat": "Resident"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "description": "Number of Goroutines currently running",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"${project}_.*\"}",
     "legendFormat": "Goroutines"
    }
   ]
  }
 ]
}